// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:402027140954:web:c713ed9df35d8ad2f54563',
    messagingSenderId: '402027140954',
    projectId: 'homeshop668ar-ar',
    authDomain: 'homeshop668ar-ar.firebaseapp.com',
    databaseURL: 'https://homeshop668ar-ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeshop668ar-ar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:402027140954:android:203075b1adc80c34f54563',
    messagingSenderId: '402027140954',
    projectId: 'homeshop668ar-ar',
    databaseURL: 'https://homeshop668ar-ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeshop668ar-ar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:402027140954:ios:b6443386e9461689f54563',
    messagingSenderId: '402027140954',
    projectId: 'homeshop668ar-ar',
    databaseURL: 'https://homeshop668ar-ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeshop668ar-ar.firebasestorage.app',
    iosBundleId: 'com.example.homeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:402027140954:ios:b6443386e9461689f54563',
    messagingSenderId: '402027140954',
    projectId: 'homeshop668ar-ar',
    databaseURL: 'https://homeshop668ar-ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeshop668ar-ar.firebasestorage.app',
    iosBundleId: 'com.example.homeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:402027140954:web:35ce09ac7b7de78af54563',
    messagingSenderId: '402027140954',
    projectId: 'homeshop668ar-ar',
    authDomain: 'homeshop668ar-ar.firebaseapp.com',
    databaseURL: 'https://homeshop668ar-ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeshop668ar-ar.firebasestorage.app',
  );
}
